name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    branches:
      - 'deploy'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Run tests
        run: coverage run -m pytest  
      - name: Tests report
        run: coverage report

  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deploy
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: build and push api
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: zahardimidov/fastapi_auth:latest

      # Deploy the Docker image (example using SSH)
      - name: Deploy to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}  # Set this secret in your repository settings
          USERNAME: ${{ secrets.SERVER_USERNAME }}  # Set this secret in your repository settings
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}  # Set this secret in your repository settings
        run: echo "$PRIVATE_KEY" > id_rsa

      - name: Set file permissions
        run: chmod 600 id_rsa
        
      - name: Set up SSH Key and Deploy my App on Server
        # run: |
        uses: appleboy/ssh-action@master
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "${DOCKER_PWD}" | docker login -u "${DOCKER_LOGIN}" --password-stdin
            docker pull zahardimidov/fastapi_auth:latest
            docker run -p 0.0.0.0:4000:4000 -d zahardimidov/fastapi_auth:latest


