
name: Docker
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
 release:
   types: [published]
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Run tests
        run: coverage run -m pytest  
      - name: Tests report
        run: coverage report
  build_and_pub:
    runs-on: [ubuntu-latest]
    needs: [run_tests]
    
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
        
    steps:
    - name: Login to docker.io
      run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - uses: actions/checkout@master
    - name: Build image
      run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
    - name: Push image to docker.io
      run: docker push $LOGIN/$NAME:${GITHUB_REF:11}